---
- hosts: "*"
  become: yes
  tasks:
    - name: Prüfe HTTP-Zugriff auf google.com
      uri:
        url: https://www.google.com
        method: GET
        return_content: no
        status_code: 200
        timeout: 5
      register: google_check
      ignore_errors: yes
    - name: Fehler anzeigen wenn google.com nicht erreichbar ist
      fail:
        msg: "google.com ist nicht erreichbar!"
      when: google_check.failed
    - name: apt dist update
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
    - name: Check that the reboot-required exists
      stat:
        path: /var/run/reboot-required
      register: p
    - name: "Require Reboot?"
      debug:
        msg: "Reboot required"
      when: p.stat.exists
